print("hello you,  mijn naam is Abdi Abdikarim")
print("wie ben jij?")
x = input("Type hier jouw naam: ")
print("hello, " + x + " aangenaam ")
print("wat is jou leeftijd? ")
y = input("Type hier jouw leeftijd: ")
print("goh wat heb jij mooi leeftijd joh." + x + y + " is mooi kerel")
